version: '3.6'

services:

  salkafka-auxtel:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE}
    container_name: salkafka-auxtel
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - REPLICATION=3
      - PARTITIONS=1
      - WAIT_ACK=1
      - CSC_LIST=ATDome ATDomeTrajectory ATAOS ATPneumatics ATHexapod ATPtg ATMCS
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      dds-network:
        ipv4_address: "139.229.170.240"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-comcam:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE}
    container_name: salkafka-comcam
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - REPLICATION=3
      - PARTITIONS=1
      - WAIT_ACK=1
      - CSC_LIST=CCHeaderService CCArchiver CCCamera
    stdin_open: true
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      dds-network:
        ipv4_address: "139.229.170.241"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-m1m3:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE}
    container_name: salkafka-m1m3
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - REPLICATION=3
      - PARTITIONS=1
      - WAIT_ACK=1
      - CSC_LIST=--file m1m3.yaml
    stdin_open: true
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      dds-network:
        ipv4_address: "139.229.170.242"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-m2:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE}
    container_name: salkafka-m2
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=Rotator Hexapod MTM2
    stdin_open: true
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      dds-network:
        ipv4_address: "139.229.170.243"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-latiss:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE}
    container_name: salkafka-latiss
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=ATArchiver ATCamera ATHeaderService ATSpectrograph
    stdin_open: true
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      dds-network:
        ipv4_address: "139.229.170.244"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-maintel:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE}
    container_name: salkafka-maintel
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=MTAOS Dome MTDomeTrajectory MTPtg
    stdin_open: true
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      dds-network:
        ipv4_address: "139.229.170.245"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-mtmount:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE}
    container_name: salkafka-mtmount
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=MTMount NewMTMount
    stdin_open: true
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      dds-network:
        ipv4_address: "139.229.170.246"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-obssys:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE}
    container_name: salkafka-obssys
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=GenericCamera Scheduler Script ScriptQueue Watcher
    stdin_open: true
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      dds-network:
        ipv4_address: "139.229.170.247"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-test:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE}
    container_name: salkafka-test
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=Test
    stdin_open: true
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      dds-network:
        ipv4_address: "139.229.170.248"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-test:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE}
    container_name: salkafka-eas
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=DIMM DSM WeatherStation
    stdin_open: true
    volumes:
      - /tmp/docker_tmp/:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      dds-network:
        ipv4_address: "139.229.170.249"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

networks:
  default:
    external:
      name: dds-network
  dds-network:
    external: true
