version: '3.6'

services:

    ataos:
        image: lsstts/ataos:DM-19890
        container_name: ataos
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}

        entrypoint: ["/home/saluser/.setup.sh"]

    atdome-csc:
        image: lsstts/at_dome:3.9-0.5
        container_name: atdome
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
 
        entrypoint: ["/home/saluser/.setup.sh"]

    atdometrajectory-sim:
        image: lsstts/at_dome_trajectory_sim:3.9-0.6a
        container_name: atdometrajectory
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}

        entrypoint: ["/home/saluser/.setup.sh"]

