services:

  develop-env:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: develop-env
    environment:
      - LSST_TOPIC_SUBNAME=${LSST_TOPIC_SUBNAME}
      - LSST_KAFKA_BROKER_ADDR=${LSST_KAFKA_BROKER_ADDR}
      - LSST_SCHEMA_REGISTRY_URL=${LSST_SCHEMA_REGISTRY_URL}
      - LSST_KAFKA_REPLICATION_FACTOR=${LSST_KAFKA_REPLICATION_FACTOR}
      - LSST_KAFKA_SECURITY_USERNAME=${LSST_KAFKA_SECURITY_USERNAME}
      - LSST_KAFKA_SECURITY_PASSWORD=${LSST_KAFKA_SECURITY_PASSWORD}
      - LSST_KAFKA_SECURITY_PROTOCOL=${LSST_KAFKA_SECURITY_PROTOCOL}
      - LSST_SITE=${LSST_SITE}
    volumes:
      - /net/scratch/tsrepos:/home/saluser/tsrepos
    tty: true
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  develop-env2:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: develop-env2
    environment:
      - LSST_TOPIC_SUBNAME=${LSST_TOPIC_SUBNAME}
      - LSST_KAFKA_BROKER_ADDR=${LSST_KAFKA_BROKER_ADDR}
      - LSST_SCHEMA_REGISTRY_URL=${LSST_SCHEMA_REGISTRY_URL}
      - LSST_KAFKA_REPLICATION_FACTOR=${LSST_KAFKA_REPLICATION_FACTOR}
      - LSST_KAFKA_SECURITY_USERNAME=${LSST_KAFKA_SECURITY_USERNAME}
      - LSST_KAFKA_SECURITY_PASSWORD=${LSST_KAFKA_SECURITY_PASSWORD}
      - LSST_KAFKA_SECURITY_PROTOCOL=${LSST_KAFKA_SECURITY_PROTOCOL}
      - LSST_SITE=${LSST_SITE}
    volumes:
      - /net/scratch/tsrepos:/home/saluser/tsrepos
    tty: true
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
