services:
  ospl-daemon:
    image: ts-dockerhub.lsst.org/ospl-daemon:${CYCLE}
    container_name: ospl-daemon
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_DDS_RESPONSIVENESS_TIMEOUT=15s
      - LSST_DDS_INTERFACE=dds
      - OSPL_INFOFILE=/tmp/ospl-info-daemon.log
      - OSPL_ERRORFILE=/tmp/ospl-error-daemon.log
    volumes:
      - ${DCO_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ${DCO_OSPL_SHMEM_DEBUG_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    restart: on-failure
    network_mode: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"
