version: "3.6"

services:

  fiberspectrograph_broadband_develop: # index 3 to be used with the AuxTel Illumination System
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: fiberspectrograph_broadband_dev
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_SITE=summit
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${DCO_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - /usr/local/lib/libavs.so.0.2.0:/usr/local/lib/libavs.so.0.2.0
      - /home/dco/develop:/home/saluser/develop
      - ./setup_dev_fiberspectrograph.sh:/home/saluser/.setup_dev.sh
    devices:
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    ipc: host
    pid: host
    network_mode: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  fiberspectrograph_broadband: # index 3 to be used with the AuxTel Illumination System
    image: ts-dockerhub.lsst.org/fiberspectrograph:${CYCLE}
    container_name: fiberspectrograph_broadband
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_SITE=summit
      - OSPL_INFOFILE=/tmp/ospl-info-fiberspectrograph3.log
      - OSPL_ERRORFILE=/tmp/ospl-error-fiberspectrograph3.log
      - RUN_ARG=3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
    volumes:
      - ${DCO_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ${DCO_OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
      - /usr/local/lib/libavs.so.0.2.0:/usr/local/lib/libavs.so.0.2.0
    devices:
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    ipc: host
    pid: host
    network_mode: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"