services:
  gc-dev:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: gc-dev
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-gc-dev.log
      - OSPL_ERRORFILE=/tmp/ospl-error-gc-dev.log
      - S3_ENDPOINT_URL=https://s3.ls.lsst.org
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
      - develop:/home/saluser/develop
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"
  gchs-dev:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: gchs-dev
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-gchs-dev.log
      - OSPL_ERRORFILE=/tmp/ospl-error-gchs-dev.log
      - S3_ENDPOINT_URL=https://s3.ls.lsst.org
      - URL_SPEC=--lfa_mode s3 --s3instance ls
      - TSTAND_HEADERSERVICE=BASE
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
      - develop:/home/saluser/develop
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"
