version: '3.6'

services:

    atmcs-sim:
        image: lsstts/at_mcs_sim:3.9-0.4
        container_name: atmcs-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
        entrypoint: ["/home/saluser/.setup.sh"]
  
    atdome-sim:
        image: lsstts/at_dome_sim:3.9-0.5
        container_name: atdome-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
 
        entrypoint: ["/home/saluser/.setup.sh"]

    atdometrajectory-sim:
        image: lsstts/at_dome_trajectory_sim:3.9-0.6a
        container_name: atdometrajectory-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
 
        entrypoint: ["/home/saluser/.setup.sh"]

    atpneumatics-sim:
        image: lsstts/at_pneumatics_sim:3.9-0.2
        container_name: atpneumatics-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
 
        entrypoint: ["/home/saluser/.setup.sh"]

    ataos-sim:
        image: lsstts/ataos:v0.2.1
        container_name: ataos-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
 
        entrypoint: ["/home/saluser/.setup.sh"]
  
    atptg-sim:
        image: tiagorib/ptkernel:new_xml
        container_name: atptg-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
 

    simulation-tests:
         image: lsstts/simulation_tests:latest
         volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
         container_name: simulation-tests
         environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
         network_mode: "host"

