version: '3.6'

services:

    atmcs-sim:
        image: lsstts/at_mcs_sim:3.9-0.4
        container_name: atmcs-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
        entrypoint: ["/home/saluser/.setup.sh"]
  
    atdome-sim:
        image: lsstts/at_dome_sim:3.9-0.5
        container_name: atdome-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
 
        entrypoint: ["/home/saluser/.setup.sh"]

    atdometrajectory-sim:
        image: lsstts/at_dome_trajectory_sim:3.9-0.6a
        container_name: atdometrajectory-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
 
        entrypoint: ["/home/saluser/.setup.sh"]

    atpneumatics-sim:
        image: lsstts/at_pneumatics_sim:3.9-0.2
        container_name: atpneumatics-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
 
        entrypoint: ["/home/saluser/.setup.sh"]

    ataos-sim:
        image: lsstts/ataos:v1.0.0
        container_name: ataos-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
 
        entrypoint: ["/home/saluser/.setup.sh"]
  
    atptg-sim:
        image: tiagorib/ptkernel:develop
        container_name: atptg-sim
        environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
        network_mode: "host"
        volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}

    hexapod-sim:
        image: couger01/hexapod_simulator
        container_name: hexapod-sim
        network_mode: "host"
 
    athexapod-sim:
      image: lsstts/ts_athexapod:3.9-dm-19762
      container_name: athexapod-sim
      environment:
        - OSPL_URI=${OSPL_URI}
        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
      network_mode: "host"
      volumes:
        - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
        - ./startCSC.sh:/home/saluser/startCSC.sh
        - ./tcpConfiguration.yaml:/home/saluser/repos/ts_salobjATHexapod/bin/settingFiles/Test/1/tcpConfiguration.yaml
      entrypoint: ["/home/saluser/startCSC.sh"]

    simulation-tests:
         image: lsstts/simulation_tests:latest
         volumes:
            - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
         container_name: simulation-tests
         environment:
            - OSPL_URI=${OSPL_URI}
            - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
         network_mode: "host"

