version: '3.6'

services:

  atptg:
    image: tiagorib/ptkernel:v1.1.0_rc2_xml4.4.1_sal4.0.0
    container_name: atptg
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
      - TELESCOPE=AuxTel
    networks:
      control-network:
        ipv4_address: "139.229.170.211"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  atdome:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0
    container_name: atdome
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    volumes:
      - ./atdome_setup.sh:/home/saluser/.setup.sh
    networks:
      control-network:
        ipv4_address: "139.229.170.212"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  atdometrajectory:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0
    container_name: atdometrajectory
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    volumes:
      - ./atdometrajectory_setup.sh:/home/saluser/.setup.sh
    networks:
      control-network:
        ipv4_address: "139.229.170.213"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  athexapod:
    image: lsstts/ts_athexapod:DM-22531
    container_name: athexapod
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "139.229.170.214"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  ataos:
    image: lsstts/ataos:DM-22130_salobj5
    container_name: ataos
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "139.229.170.215"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  atheaderservice:
    image: lsstts/at_headerservice:v1.2.0_salobj_v5.0.0_xml_v4.4.1
    container_name: atheaderservice
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    volumes:
      - ./aths_setup.sh:/home/saluser/.setup.sh
    networks:
      control-network:
        ipv4_address: "139.229.170.223"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  atspectrograph:
    image: lsstts/atspectrograph:v0.3.1_sal_v4.0.0_salobj_v5.0.0
    container_name: atspectrograph
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "139.229.170.230"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

networks:
  default:
    external:
      name: control-network
  control-network:
    external: true
