version: '3.6'

services:

  atptg:
    image: ts-dockerhub.lsst.org/ptkernel:v1.1.0_rc3_b22
    container_name: atptg
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
      - TELESCOPE=AuxTel
    networks:
      control-network:
        ipv4_address: "139.229.170.231"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  atdome:
    image: lsstts/develop-env:b36
    container_name: atdome
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    volumes:
      - ./atdome_setup.sh:/home/saluser/.setup.sh
    networks:
      control-network:
        ipv4_address: "139.229.170.232"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  atdometrajectory:
    image: lsstts/develop-env:b22
    container_name: atdometrajectory
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    volumes:
      - ./atdometrajectory_setup.sh:/home/saluser/.setup.sh
    networks:
      control-network:
        ipv4_address: "139.229.170.233"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  athexapod:
    image: lsstts/ts_athexapod:v0.3.0_b31
    container_name: athexapod
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "139.229.170.234"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  ataos:
    image: lsstts/ataos:v1.5.0
    container_name: ataos
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "139.229.170.235"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  atheaderservice:
    image: lsstts/at_headerservice:v1.3.1_salobj_v5.0.0_xml_v4.6.0
    container_name: atheaderservice
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    volumes:
      - ./aths_setup.sh:/home/saluser/.setup.sh
      - /home/saluser/ATHS_data/www/:/home/saluser/www/
    networks:
      control-network:
        ipv4_address: "139.229.170.236"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  atspectrograph:
    image: lsstts/atspectrograph:DM-22731_sal_v4.0.0_salobj_v5.0.0
    container_name: atspectrograph
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "139.229.170.230"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

networks:
  default:
    external:
      name: control-network
  control-network:
    external: true
