version: '3.6'

services:

  atptg:
    image: tiagorib/ptkernel:v1.1rev0_xml4.2rev0_sal3.10
    container_name: atptg
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "192.168.1.211"

  atdome:
    image: lsstts/at_dome:v0.7.0
    container_name: atdome
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "192.168.1.212"

  atdometrajectory:
    image: lsstts/at_dome_trajectory:v1.0.0
    container_name: atdometrajectory
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "192.168.1.213"

  athexapod:
    image: lsstts/ts_athexapod:v0.2.0_xmlv4.2rev0_sal3.10.0_salobj3.12.0
    container_name: athexapod
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "192.168.1.214"
    volumes:
      - ./ATHexapod/startCSC.sh:/home/saluser/startCSC.sh
      - ./ATHexapod/tcpConfiguration.yaml:/home/saluser/repos/ts_salobjATHexapod/bin/settingFiles/Test/1/tcpConfiguration.yaml
    entrypoint: ["/home/saluser/startCSC.sh"]

  ataos:
    image: lsstts/ataos:v1.2.0
    container_name: ataos
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "192.168.1.215"

networks:
  default:
    external:
      name: control-network
  control-network:
    external: true
