# The different daemons are meant for different Tucson machines:
# ospl-loonie - loonie.tu.lsst.org

services:
  ospl-loonie:
    image: ts-dockerhub.lsst.org/ospl-daemon:${CYCLE}
    container_name: ospl-daemon
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_DDS_RESPONSIVENESS_TIMEOUT=15s
      - LSST_DDS_INTERFACE=enp1s0.3085
      - OSPL_INFOFILE=/tmp/ospl-info-daemon.log
      - OSPL_ERRORFILE=/tmp/ospl-error-daemon.log
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ${CAL_OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    network_mode: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"
