version: "3.6"

services:

  electrometer1: # index1, for use on Loonie with the AuxTel Illumination System
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: electrometer1
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_electrometer.sh:/home/saluser/.setup_dev.sh
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  electrometer2: # index2, for use on Toonie with the CIMACS
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: electrometer2
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_electrometer.sh:/home/saluser/.setup_dev.sh
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  electrometer3: # index3, for use with the laser Fiber Coupler
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: electrometer3
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_electrometer.sh:/home/saluser/.setup_dev.sh
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  electrometer4: # index4, for use with CIMACs, 2nd sensor
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: electrometer4
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=4
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_electrometer.sh:/home/saluser/.setup_dev.sh
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  electrometer5: # index5, for use with CIMACs, 3rd sensor, placement not decided
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: electrometer5
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=5
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_electrometer.sh:/home/saluser/.setup_dev.sh
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  electrometer6: # index 6, laser monitor
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: electrometer6
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=6
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_electrometer.sh:/home/saluser/.setup_dev.sh
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  atmonochromator:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: atmonochromator
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_atmonochromator.sh:/home/saluser/.setup_dev.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  fiberspectrograph_broadband: # index 3 to be used with the AuxTel Illumination System
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: fiberspectrograph_broadband
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - /usr/local/lib/libavs.so.0.2.0:/usr/local/lib/libavs.so.0.2.0
      - ~/develop:/home/saluser/develop
      - ./setup_dev_fiberspectrograph.sh:/home/saluser/.setup_dev.sh
    devices:
      - /dev/usb/bus:/dev/usb/bus
    privileged: true
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  fiberspectrograph_red: # index 2 to be used with the Main Telescope
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: fiberspectrograph_red
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - /usr/local/lib/libavs.so.0.2.0:/usr/local/lib/libavs.so.0.2.0
      - ~/develop:/home/saluser/develop
      - ./setup_dev_fiberspectrograph.sh:/home/saluser/.setup_dev.sh
    devices:
      - /dev/usb/bus:/dev/usb/bus
    privileged: true
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  fiberspectrograph_blue: # index 1 to be used with the Main Telescope
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: fiberspectrograph_blue
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - /usr/local/lib/libavs.so.0.2.0:/usr/local/lib/libavs.so.0.2.0
      - ~/develop:/home/saluser/develop
      - ./setup_dev_fiberspectrograph.sh:/home/saluser/.setup_dev.sh
    devices:
      - /dev/usb/bus:/dev/usb/bus
    privileged: true
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  igusxaxis: # Along the floor, generally index 1
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: igusxaxis
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=1
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_linearstage.sh:/home/saluser/.setup_dev.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  igusyaxis: # Vertical, generally index 2
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: igusyaxis
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=2
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_linearstage.sh:/home/saluser/.setup_dev.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  laser:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: laser
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_tunablelaser.sh:/home/saluser/.setup_dev.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  atwhitelight:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: atwhitelight
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_atwhitelight.sh:/home/saluser/.setup_dev.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  cbp:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: cbp
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_cbp.sh:/home/saluser/.setup_dev.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  ledprojector:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: ledprojector
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_ledprojector.sh:/home/saluser/.setup_dev.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  zaberstage1:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: zaberstage1
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=3
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_linearstage.sh:/home/saluser/.setup_dev.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  zaberstage2: # LED Selector
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: zaberstage2
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=4
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_linearstage.sh:/home/saluser/.setup_dev.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  zaberstage3: # Vertical
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: zaberstage3
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=5
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_linearstage.sh:/home/saluser/.setup_dev.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  zaberstage4: # LED Focus
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: zaberstage4
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - CSC_INDEX=6
    volumes:
      - ${CAL_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ~/develop:/home/saluser/develop
      - ./setup_dev_linearstage.sh:/home/saluser/.setup_dev.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"
