services:
  fiberspectrograph_blue:
    image: ts-dockerhub.lsst.org/fiberspectrograph:${CYCLE}
    container_name: fiberspectrograph_blue
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_SITE=summit
      - OSPL_INFOFILE=/tmp/ospl-info-fiberspectrograph.log
      - OSPL_ERRORFILE=/tmp/ospl-error-fiberspectrograph.log
      - RUN_ARG=102
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
    volumes:
      - ${DCO_OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ${DCO_OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
      - /usr/local/lib/libavs.so.0.2.0:/usr/local/lib/libavs.so.0.2.0
    devices:
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    ipc: host
    pid: host
    network_mode: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"