version: '3.6'

services:
#        EFD_Updater:
#                image: lsstts/efd_writers
#                volumes:
#                        - ./efd_population.sh:/home/saluser/efd_population.sh
#                network_mode: "host"
#                entrypoint: ["/home/saluser/efd_population.sh"]

        EFD_MariaDB:
                image: mariadb:latest
                environment:
                        - MYSQL_ROOT_PASSWORD=lssttest
                        - MYSQL_DATABASE=EFD
                        - MYSQL_USER=efduser
                        - MYSQL_PASSWORD=lssttest
                volumes:
                        - ${HOME}/efd_xml_v3.10.2/mysql:/var/lib/mysql
                networks:
                        control-network:
                                ipv4_address: "192.168.1.2"

        EFD_ATDome_command:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                networks:
                        control-network:
                                ipv4_address: "192.168.1.3"
                entrypoint: ["/home/saluser/efd_writers.sh", "ATDome", "command", "efdwriter"]
        
        EFD_ATDome_event:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                networks:
                        control-network:
                                ipv4_address: "192.168.1.14"
                entrypoint: ["/home/saluser/efd_writers.sh", "ATDome", "event", "efdwriter"]

        EFD_ATDome_telemetry:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                networks:
                        control-network:
                                ipv4_address: "192.168.1.15"
                entrypoint: ["/home/saluser/efd_writers.sh", "ATDome", "telemetry", "efdwriter"]

        EFD_ATHexapod_command:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.4"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATHexapod", "command" , "efdwriter"]

        EFD_ATHexapod_event:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.16"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATHexapod", "event" , "efdwriter"]

        EFD_ATHexapod_telemetry:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.17"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATHexapod", "telemetry" , "efdwriter"]


        EFD_ATMCS_command:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.6"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATMCS", "command" , "efdwriter"]

        EFD_ATMCS_event:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.18"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATMCS", "event" , "efdwriter"]

        EFD_ATMCS_telemetry:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.19"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATMCS", "telemetry" , "efdwriter"]
        
        EFD_ATptg_command:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.7"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATPtg", "command" , "efdwriter"]

        EFD_ATptg_event:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.35"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATPtg", "event" , "efdwriter"]
        
        EFD_ATptg_telemetry:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.20"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATPtg", "telemetry" , "efdwriter"]

        EFD_ATDomeTrajectory_command:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.8"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATDomeTrajectory", "command" , "efdwriter"]

        EFD_ATDomeTrajectory_event:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.22"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATDomeTrajectory", "event" , "efdwriter"]

        EFD_ATDomeTrajectory_telemetry:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.23"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATDomeTrajectory", "telemetry" , "efdwriter"]

        EFD_ATPneumatics_command:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.9"
                volumes:
                        - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATPneumatics", "command" , "efdwriter"]

        EFD_ATPneumatics_event:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.24"
                volumes:
                        - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATPneumatics", "event" , "efdwriter"]

        EFD_ATPneumatics_telemetry:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.25"
                volumes:
                        - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATPneumatics", "telemetry" , "efdwriter"]

        EFD_ATAOS_command:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.10"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATAOS", "command" , "efdwriter"]

        EFD_ATAOS_event:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.26"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATAOS", "event" , "efdwriter"]

        EFD_ATAOS_telemetry:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.27"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ATAOS", "telemetry" , "efdwriter"]
        
        EFD_DIMM_command:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.11"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "DIMM", "command" , "efdwriter"]

        EFD_DIMM_event:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.28"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "DIMM", "event" , "efdwriter"]

        EFD_DIMM_telemetry:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.29"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "DIMM", "telemetry" , "efdwriter"]
        
        EFD_Scripts_command:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.12"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "Scripts", "command" , "efdwriter"]

        EFD_Scripts_event:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.30"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "Scripts", "event" , "efdwriter"]

        EFD_Scripts_telemetry:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.32"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "Scripts", "telemetry" , "efdwriter"]


        EFD_ScriptQueue_command:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.13"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ScriptQueue", "command" , "efdwriter"]
        
        EFD_ScriptQueue_event:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.33"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ScriptQueue", "event" , "efdwriter"]
        
        EFD_ScriptQueue_telemetry:
                image: lsstts/efd_writers:DM-20584
                environment:
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - LSST_EFD_HOST=${LSST_EFD_HOST}
                        - LSST_KAFKA_BROKERS=localhost
                networks:
                        control-network:
                                ipv4_address: "192.168.1.34"
                volumes:
                        - ./efd_writers.sh:/home/saluser/efd_writers.sh
                entrypoint: ["/home/saluser/efd_writers.sh" , "ScriptQueue", "telemetry" , "efdwriter"]

networks:
  default:
    external:
      name: control-network
  control-network:
    external: true
