version: "3.4"

services:

  salkafka:
    image: lsstts/salkafka:v1.0b1_xml4.2rev0
    container_name: salkafka_producer
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
      - BROKER_IP=summit-efd0.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://summit-registry-efd.lsst.codes
      - REPLICATION=1
      - LOG_LEVEL=10
      - CSC_LIST=ATPtg ATHexapod ATMCS ATDome ATDomeTrajectory ATPneumatics ATAOS Environment DIMM GenericCamera ScriptQueue Script
    volumes:
      - $PWD/ospl_2.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
    stdin_open: true
    tty: true
    networks:
      zbridge:
      control-network:
        ipv4_address: "192.168.1.2"

networks:
  default:
    external:
      name: control-network
  control-network:
    external: true
  zbridge:
