services:
  ess-controller:
    image: lsstts/ess-controller-aarch64:${CYCLE}.000
    container_name: ess-controller
    volumes:
      - /dev:/dev
    tty: true
    privileged: true
    network_mode: host
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"
  
  audiotrigger-controller:
    image: lsstts/audiotrigger-controller-aarch64:${CYCLE}${audiotrigger_rev}
    container_name: audiotrigger-controller
    volumes:
      - /dev:/dev
      - /usr/share/alsa:/usr/share/alsa
    group_add:
      - audio
    tty: true
    privileged: true
    network_mode: host
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      RUN_ARG: "--disable-microphone"
