version: '3.6'

services:

  environment:
    image: lsstts/environment:v1.0.0_sal_v4.0.0_salobj_v5.0.0
    container_name: environment
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "139.229.170.220"

  dimm:
    image: lsstts/dimm:v0.2.0_sal_v4.0.0_salobj_v5.0.0
    container_name: dimm
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
      - CSC_INDEX=1
    networks:
      control-network:
        ipv4_address: "139.229.170.219"

  dimm_2:
    image: lsstts/dimm:v0.2.0_sal_v4.0.0_salobj_v5.0.0
    container_name: dimm_2
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
      - CSC_INDEX=2
    networks:
      control-network:
        ipv4_address: "139.229.170.222"

  ingester:
    image: lsstsqre/centos:7-stack-lsst_distrib-w_2019_44
    container_name: ingester
    volumes:
      - /home/saluser/ingest/:/home/lsst/ingest/
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
      - ./ingester_setup.sh:/home/lsst/.setup.sh
    stdin_open: true
    tty: true
    entrypoint: ["/home/lsst/.setup.sh"]

  watcher:
    image: lsstts/watcher:v1.0.2_rc1
    container_name: watcher
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    networks:
      control-network:
        ipv4_address: "139.229.170.221"

  queue:
    image: lsstts/develop-env:b45
    container_name: queue
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    volumes:
      - ./at_queue_setup.sh:/home/saluser/.setup.sh
    stdin_open: true
    tty: true
    networks:
      control-network:
        ipv4_address: "139.229.170.229"

  at_scheduler:
    image: lsstts/scheduler:DM-23757_b45
    container_name: at_scheduler
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
      - INDEX=2
    volumes:
      - /net/scratch/at-scheduler:/home/saluser/data
    stdin_open: true
    tty: true
    networks:
      control-network:
        ipv4_address: "139.229.170.237"

networks:
  default:
    external:
      name: control-network
  control-network:
    external: true
