version: "3.4"

services:

  # user: Patrick
  diag01:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0_b27
    container_name: diag01
    environment:
      - LSST_DDS_DOMAIN=$LSST_DDS_DOMAIN
    volumes:
      - $HOME/develop_diag01:/home/saluser/develop
      - ./diag01_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./diag01_setup.sh:/home/saluser/.setup.sh
      - ./ospl_201.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
    stdin_open: true
    tty: true
    networks:
      bridge:
      control-network:
        ipv4_address: "139.229.170.201"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  # user: Eric
  diag02:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0_b27
    container_name: diag02
    environment:
      - LSST_DDS_DOMAIN=$LSST_DDS_DOMAIN
    volumes:
      - $HOME/develop_diag02:/home/saluser/develop
      - ./diag02_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./diag02_setup.sh:/home/saluser/.setup.sh
      - ./ospl_202.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
    stdin_open: true
    tty: true
    networks:
      control-network:
        ipv4_address: "139.229.170.202"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  # user: Tiago
  diag03:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0_b27
    container_name: diag03
    environment:
      - LSST_DDS_DOMAIN=$LSST_DDS_DOMAIN
    volumes:
      - $HOME/develop_diag03:/home/saluser/develop
      - ./diag03_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./diag03_setup.sh:/home/saluser/.setup.sh
      - ./ospl_203.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
    stdin_open: true
    tty: true
    networks:
      control-network:
        ipv4_address: "139.229.170.203"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  # user: Brian
  diag04:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0_b27
    container_name: diag04
    environment:
      - LSST_DDS_DOMAIN=$LSST_DDS_DOMAIN
    volumes:
      - $HOME/develop_diag04:/home/saluser/develop
      - ./diag04_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./diag04_setup.sh:/home/saluser/.setup.sh
      - ./ospl_204.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
    stdin_open: true
    tty: true
    networks:
      control-network:
        ipv4_address: "139.229.170.204"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  # user: Robert
  diag05:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0_b27
    container_name: diag05
    environment:
      - LSST_DDS_DOMAIN=$LSST_DDS_DOMAIN
    volumes:
      - $HOME/develop_diag05:/home/saluser/develop
      - ./diag05_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./diag05_setup.sh:/home/saluser/.setup.sh
      - ./ospl_205.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
    stdin_open: true
    tty: true
    networks:
      control-network:
        ipv4_address: "139.229.170.205"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  # user: Kevin Reil
  diag06:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0_b27
    container_name: diag06
    environment:
      - LSST_DDS_DOMAIN=$LSST_DDS_DOMAIN
    volumes:
      - $HOME/develop_diag06:/home/saluser/develop
      - ./diag06_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./diag06_setup.sh:/home/saluser/.setup.sh
      - ./ospl_206.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
    stdin_open: true
    tty: true
    networks:
      control-network:
        ipv4_address: "139.229.170.206"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  # user: cslange
  diag07:
    image: lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0_b27
    container_name: diag07
    environment:
      - LSST_DDS_DOMAIN=$LSST_DDS_DOMAIN
    volumes:
      - $HOME/develop_diag07:/home/saluser/develop
      - ./diag07_notebook_config.py:/home/saluser/.jupyter/jupyter_notebook_config.py
      - ./diag07_setup.sh:/home/saluser/.setup.sh
      - /mnt/dmcs/:/mnt/dmcs
      - /mnt/data/:/mnt/data
    stdin_open: true
    tty: true
    networks:
      control-network:
        ipv4_address: "139.229.170.207"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  firefly:
    image: ipac/firefly:lsst-dev
    container_name: firefly
    environment:
      - ADMIN_PASSWORD=$ADMIN_PASSWD
      - MANAGER=FALSE
      - FIREFLY_OPTS="-Dvisualize.fits.search.path=/scratch/firefly"
      - FIREFLY_SHARED_WORK_DIR="/scratch/firefly/workarea"
      - MAX_JVM_SIZE=64G
      - DEBUG=false
    volumes:
      - /scratch
    networks:
      control-network:
        ipv4_address: "139.229.170.210"

networks:
  default:
    external:
      name: control-network
  control-network:
    external: true
  bridge:
