services:
  ess-controller:
    image: lsstts/ess-controller-aarch64:${CYCLE}${camera_ess01_rev}
    container_name: ess-controller
    devices:
      - /dev/ttyAMA2:/dev/serial1
    tty: true
    network_mode: host
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"
