version: "3"

services:
        dimm:
                image: lsstts/dimm:DM-19900
                environment:
                        - OSPL_URI=${OSPL_URI}
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                network_mode: "host"
                container_name: dimm
                volumes:
                        - ./dimm_ospl.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
                        - ./config.yaml:/home/saluser/repos/ts_dimm/python/lsst/ts/dimm/config/config.yaml
        dimm_2:
                image: lsstts/dimm:DM-19900
                environment:
                        - OSPL_URI=${OSPL_URI}
                        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
                        - INDEX_CSC=2
                network_mode: "host"
                container_name: dimm_2
                volumes:
                        - ./dimm_ospl.xml:/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux/etc/config/ospl.xml
                        - ./config_2.yaml:/home/saluser/repos/ts_dimm/python/lsst/ts/dimm/config/config.yaml
