version: "3.6"

services:

  develop-env:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: develop-env
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - LSST_SITE=${LSST_SITE}
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
      - S3_ENDPOINT_URL=https://s3.tu.lsst.org
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
      - /home/dco/develop:/home/saluser/develop
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"
  integration-tester-dev:
    image: ts-dockerhub.lsst.org/integrationtests:${CYCLE}
    container_name: integration-tester-dev
    environment:
      - LSST_DDS_PARTITION_PREFIX=${SITE_PARTITION_PREFIX}
      - OSPL_INFOFILE=/tmp/ospl-info-inttester.log
      - OSPL_ERRORFILE=/tmp/ospl-error-inttester.log
      - RUN_ARG=/bin/bash
    volumes:
      - ${OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
      - /deploy-lsstts/develop:/home/saluser/develop
      - /deploy-lsstts/reports:/home/saluser/robotframework_EFD/Reports
      - ./setup_integration_tester.sh:/home/saluser/.startup.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"
