services:

  develop-env:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    container_name: develop-env
    environment:
      - LSST_TOPIC_SUBNAME=${LSST_TOPIC_SUBNAME}
      - LSST_KAFKA_BROKER_ADDR=${LSST_KAFKA_BROKER_ADDR}
      - LSST_SCHEMA_REGISTRY_URL=${LSST_SCHEMA_REGISTRY_URL}
      - LSST_KAFKA_SECURITY_USERNAME=${LSST_KAFKA_SECURITY_USERNAME}
      - LSST_KAFKA_SECURITY_PASSWORD=${LSST_KAFKA_SECURITY_PASSWORD}
      - LSST_KAFKA_SECURITY_PROTOCOL=${LSST_KAFKA_SECURITY_PROTOCOL}
      - LSST_SITE=${LSST_SITE}
      - S3_ENDPOINT_URL=https://s3.tu.lsst.org
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MYS3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MYS3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - /home/dco/develop:/home/saluser/develop
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"
  integration-tester-dev:
    image: ts-dockerhub.lsst.org/integrationtests:${CYCLE}
    container_name: integration-tester-dev
    environment:
      - LSST_TOPIC_SUBNAME=${LSST_TOPIC_SUBNAME}
      - LSST_KAFKA_BROKER_ADDR=${LSST_KAFKA_BROKER_ADDR}
      - LSST_SCHEMA_REGISTRY_URL=${LSST_SCHEMA_REGISTRY_URL}
      - LSST_KAFKA_SECURITY_USERNAME=${LSST_KAFKA_SECURITY_USERNAME}
      - LSST_KAFKA_SECURITY_PASSWORD=${LSST_KAFKA_SECURITY_PASSWORD}
      - LSST_KAFKA_SECURITY_PROTOCOL=${LSST_KAFKA_SECURITY_PROTOCOL}
      - LSST_SITE=${LSST_SITE}
      - RUN_ARG=/bin/bash
    volumes:
      - /home/dco/develop:/home/saluser/develop
      - /home/dco/reports:/home/saluser/robotframework_EFD/Reports
      - ./setup_integration_tester.sh:/home/saluser/.startup.sh
    tty: true
    ipc: host
    pid: host
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"
